spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.210.224:3306/patient?user=root&password=Iamthesudoer&useSSL=false
    username: root
    password: 6b8764d58be0fd79
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  port: 8020